### PR TITLE
Issue 1521: Move the images for the Nuget (Visual Studio) example from the old wiki to the new one

### LINKED ISSUE #1521: Move the images for the Nuget (Visual Studio) example from the old wiki to the new one
# Task Description

We have migrated our wiki from [the strongbox project](https://github.com/strongbox/strongbox/wiki) to [strongbox-docs](https://strongbox.github.io/) project. We appear to have some images still pointing to the old wiki and this prevents us from being able to shut down the old wiki, which is now obsolete and might be misleading people.

# Tasks

The following tasks will need to be carried out:
* [ ] Clone the docs from `git@github.com:strongbox/strongbox-docs` 
* [ ] Then move the images necessary images from `wiki/**` under `resources/images/nuget/` to `docs/assets/images` under the [`strongbox-docs`](https://github.com/strongbox/strongbox-docs/) repository. Make sure to preserve git history!
* [ ] Change the link for the images in the [hello-strongbox-nuget-visual-studio](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-nuget-visual-studio) to point to the new locations.
* [ ] Check if there are other images which have not been migrated and report/fix them.

# Useful Links

* [strongbox-docs](https://github.com/strongbox/strongbox-docs/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

### PR DESCRIPTION
**Pull request by JekRock**
Fixes strongbox/strongbox#1521

- Copy images from wiki/resources/images/nuget/ to docs/assets/images/

### CODE REVIEW

**Comment by steve-todorov** [comment]
Hi @JekRock and thanks for your contribution! :)

It looks like there was a typo in the requirement which might have confused you into just copying the files. Apologize. 

Can you force `reset` your branch's head to the `master` and use `git mv` instead of copying the files? This should preserve the git history of the file (i.e. authors, etc) which is important.

**Comment by JekRock** [comment]
Hi @steve-todorov !
Sorry about that. I'll fix it

**Comment by JekRock** [comment]
@steve-todorov I've moved images with git mv. Could you please check it?

**Review by steve-todorov — APPROVED** [review]
LGTM! Thanks! :)

**Comment by carlspring** [comment]
Thanks for your help! :)

**Pull request merged**
