### PR TITLE
Issue 1100 :  Filename too long solution for Windows.

### PR DESCRIPTION
**Pull request by msarfrazanwar**
Added the solution in documents.

Windows 10 workaround for strongbox/strongbox#1100.

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution and congratulations on your first pull request!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Kind regards,

Martin

**Comment by carlspring** [comment]
@msarfrazanwar ,

Would you be able to try this workaround on a Windows 7 box as well?

**Comment by msarfrazanwar** [comment]
@carlspring I don't have Win 7 but I will see if possible.

**Comment by steve-todorov** [comment]
@msarfrazanwar congratulations on your first contribution! :)

**Pull request merged**
