### PR TITLE
Fixed broken link to ICLA.pdf

### PR DESCRIPTION
**Pull request by Shubhang**

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Kind regards,

Martin

**Comment by Shubhang-Sharma** [comment]
is the ICLA really required for minor documentation fixes?

**Comment by Shubhang** [comment]
Is the ICLA really required for minor documentation fixes?

**Comment by carlspring** [comment]
@Shubhang-Sharma ,

If you'll be contributing on a more regular basis - yes. I appreciate that this change is quite trivial and thank you for fixing it.]

**Comment by carlspring** [comment]
Thanks for the fixes and for signing the ICLA! :)

**Pull request merged**
